branch-defaults:
  master:
    environment: wirent-env
environment-defaults:
  wirent-env:
    branch: null
    repository: null
global:
  application_name: wirent
  default_ec2_keyname: wirent
  default_platform: 64bit Amazon Linux 2016.09 v2.3.3 running PHP 7.0
  default_region: ap-southeast-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
